<img src="numpy-hd.jpg">

## Slicing, Stacking Arrays and Indexing with boolean arrays<br>
This tutorial covers array operations such as slicing, indexing, stacking. We will also go over how to index one array with another boolean array.<br><br>

In [14]:
import numpy as np

**Indexing and Slicing**

In [16]:
n = [6,7,8]
n[0:2] # To display the first two elements in the list

[6, 7]

<img src="slicing.png" height="350" width="350" align="left">

In [18]:
n[-1] # Print or start from the last element

8

A Numpy array supports a similar type of slicing...

In [20]:
a = np.array([6,7,8])
a[0:2] # This gives you the same result as with the Python list above

array([6, 7])

In [21]:
a[-1] # It also supports the reverse index, again, just like a Python list

8

**Multi-Dimensional Array**<br>

In [24]:
b = np.array([[6,7,8], [1,2,3], [9,3,2]])
b

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [26]:
b[1,2]

3

When you issue the above command/slice, you are first going to the row one (ie row zero then one) and then you are going to column two (ie column zero, one and then two)<br>
<img src="mda.png" height="350" width="350" align="left">

When we do something like this...

In [28]:
b[0:2,2]

array([8, 3])

...it goes through zero to the second row and remember that is zero and row one as the las number here is not counted. Then it will print the second element which in rows zero and one is 8 & 3...<br>
<img src ="mda2.png" height="350" width="350" align="left">

In [29]:
b[-1] # Again this is the last element in the array. In this case we have three of them & Numpy prints them all out

array([9, 3, 2])

In [30]:
b[-1, 0:2] # Int he last row, print the first two elements (0 & 1) forgetting the 2 on the end

array([9, 3])

To go through all the rows and print the last two columns is...

In [31]:
b[:, 1:3] # The syntax for all is just the colon. We have to specify 1:3 so that it ignores column 3 and gives us what we want

array([[7, 8],
       [2, 3],
       [3, 2]])

If we were to say 1:2 then it would ignore the 2 and just give us column 1

**Iterarte through arrays**

In [34]:
c = np.array([[6,7,8], [1,2,3], [9,3,2]]) # This is the array that we are going to use again
c

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

To iterate through the array, you can just say...

In [35]:
for row in c:
    print (row)

[6 7 8]
[1 2 3]
[9 3 2]


To flatten the array and print every cell

In [36]:
for cell in c.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


**Stacking two arrays together**<br>
Let's take these two arrays...

In [37]:
d = np.arange(6).reshape(3,2)
e = np.arange(6,12).reshape(3,2)
d, e # This is what the arrys look like

(array([[0, 1],
        [2, 3],
        [4, 5]]), array([[ 6,  7],
        [ 8,  9],
        [10, 11]]))

To stack one on top of the other, like two boxes, you would...

In [44]:
np.vstack((d, e)) # This is not returning the expected result at all

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

There is also a thing called horizontal stacking...

In [45]:
np.hstack((d, e)) # Where they are stacked side-by-side

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

**Horizontal Split...**

In [46]:
f = np.arange(30).reshape(2,15) # New array of 30 elements that are reshaped into 2 rows and 15 columns
f

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

We are going to slice it into three equally sized arrays

In [47]:
np.hsplit(f, 3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

It has not been displayed very well but everywhere you see the word array that is the start of a new array. If we store the results in a variable, we can then print them one-by-one to make it more obvious...

In [48]:
split = np.hsplit(f, 3)
split[0] # This is the first array that hsplit created

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [49]:
# This is the second array that hsplit created
split[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [50]:
# This is the third array that hsplit created
split[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

We can also split them vertically but as we only have rows, we can only split it twice...

In [52]:
vert = np.vsplit(f, 2)
vert[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [53]:
vert[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

**Indexing with boolean arrays**<br>
This is very powerful

In [56]:
g = np.arange(12).reshape(3, 4) # This is a very popular way of creating arrays and then shaping them to your requirements
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
# We create our variable and set it to be is the element in g greater than 4
h = g > 4 
h

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

This iterates through our array g and outputs another array with False where the element in g is less than 4 and True where the element in g is greater than 4. The individual results are stored in this new array.<br>
Now have a look at this, we are going to use our original array and pass it the boolean array as an argument, let's see what it does...

In [58]:
g[h]

array([ 5,  6,  7,  8,  9, 10, 11])

What's happened here is that it has looked through the h array and wherever it found a True value, it returned those elements from g (ie in their original numerical form)<br>
You can use this, for example, to replace all the elements with a specific value...

In [61]:
g[h]=-1
g

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

Now we see that all the elements that are greater than four are now represented by the interger -1. Not sure where you would use this tho.