<img src="numpy-hd.jpg">

## Iterate Numpy Array Using nditer<br>
nditer can be used to iterate through numpy array in variety of ways. C style and F style iteration is possible using flags in nditer. You can also iterate two broadcastable arrays concurrently using nditer

In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**The simple way to iterate through this array is to use a for loop...**

In [3]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


To print all the individual elements in the array...we just have to add an extra line

In [4]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


If we want to flatten the array before we run the for loop, we can use the flatten function...

In [5]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


**nditer**<br>
Allows for more sophisticated iterations

In [6]:
#To get the same result as flatten
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


The 'C' order means that you are printing row zero, in order, first, then you go down to row 1 and then print that in order etc...<br>
<img src="c-order.png" align="left">

In [7]:
#To get the fortran order
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


...and now, the array is printed in column order<br>
<img src="fortran.png" align="left">

**external_loop**<br>To print in Fortran order but print a whole column, instead of the individual elements, with each iteration can be achieved...

In [8]:
for x in np.nditer(a, flags=['external_loop'],order='F'):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


**Modify array values while iterating**

In [9]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x

In [10]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

**Iterate two broadcastable arrays concurrently**<br>
Broadcastable simply means that either their shape should be the same or one of the dimensions in one of the arrays should be one.<br>
**NOTE:** You can only do this with broadcastablke arrays

In [12]:
#First we'll create our second array
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [13]:
#Now we will iterate through them both at the same time
for x, y in np.nditer([a,b]):
    print (x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


To learn more aqbout nditer, visit https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.nditer.html and for more about broadcastable arrays, visit https://docs.scipy.org/doc/numpy-1.14.0/user/basics.broadcasting.html